### ISSUE TITLE
cannot import

### ISSUE THREAD

**Issue by irmakakyeli** [dimatura/binvox-rw-py#14]
I am working on google colab and trying to run an already existing code. However, the import of binvox_rw is not working and even with the manual download option, there is an error with the download and it does not work. I could not find any solution yet. Can you help me, please?

![unknown](https://user-images.githubusercontent.com/45370715/128562431-f5511608-462e-4b73-a89b-1d6790025238.png)

**Comment by grEmsIsY** [comment]
@irmakakyeli  How to fix it guy? Thank you?

**Comment by irmakakyeli** [comment]
it is not included like other libraries so just download the file binvox_rw and put it in your project

> @irmakakyeli How to fix it guy? Thank you?
